cache:
  paths:
    - env

python2:
    script:
        - virtualenv env --system-site-packages && source env/bin/activate
        - cd entparse
        - pip install -r requirements.txt
        - pip install -e . --no-deps
        - py.test test/test.py
